version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3000}:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT:-3000}/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    # If you use file watchers in dev, you could mount volumes (commented out for prod)
#    volumes:
#      - .:/app
#      - /app/node_modules
